name: Java CI with JUnit 5

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Bha15_vya34
          MYSQL_DATABASE: ecommerce
        options: >-
          --health-cmd="mysqladmin ping -h localhost -pBha15_vya34"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Create lib folder
        run: mkdir -p lib

      - name: Download JUnit 5 Console Standalone
        run: curl -L -o lib/junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.3/junit-platform-console-standalone-1.11.3.jar

      - name: Download MySQL Connector/J
        run: curl -L -o lib/mysql-connector-j-9.4.0.jar https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.4.0/mysql-connector-j-9.4.0.jar

      - name: Wait for MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          until mysql -h 127.0.0.1 -P 3306 -u root -pBha15_vya34 -e "SELECT 1" ecommerce; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      # Optional: Run schema.sql if you want to auto-create tables in CI
      # - name: Setup database schema
      #   run: |
      #     mysql -h 127.0.0.1 -P 3306 -u root -pBha15_vya34 ecommerce < schema.sql

      - name: Compile Java code
        run: javac -cp ".:lib/*" src/code/main/*.java src/code/model/*.java src/code/controller/*.java src/tests/*.java

      - name: Run JUnit tests
        run: java -cp ".:lib/*:src" org.junit.platform.console.ConsoleLauncher --scan-class-path
