name: Java CI with JUnit 5

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ecommerce
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Create lib folder
      run: mkdir -p lib

    - name: Download JUnit 5 Console Standalone
      run: curl -L -o lib/junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.3/junit-platform-console-standalone-1.11.3.jar

    - name: Download MySQL Connector/J
      run: curl -L -o lib/mysql-connector-j-9.4.0.jar https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-9.4.0.jar

    - name: Compile Java code
      run: javac -cp ".:lib/*" src/code/main/*.java src/code/model/*.java src/code/controller/*.java src/tests/*.java

    - name: Run JUnit tests
      env:
        DB_URL: jdbc:mysql://127.0.0.1:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
        DB_USER: test
        DB_PASSWORD: test
      run: java -cp ".:lib/*:src" org.junit.platform.console.ConsoleLauncher --scan-class-path
