name: Java CI with JUnit 5

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Create lib folder
      run: mkdir -p lib

    - name: Download JUnit 5 Console Standalone
      run: curl -L -o lib/junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.3/junit-platform-console-standalone-1.11.3.jar

    - name: Compile Java code
      run: javac -cp ".:lib/*" main/*.java view/*.java model/*.java controller/*.java tests/*.java

    - name: Run JUnit tests
      run: java -cp ".:lib/*" org.junit.platform.console.ConsoleLauncher --scan-class-path
